"""Prepare model module for the RC pipeline.

Performs mesh cleanup, smoothing, and hole closing on a model that
has already been generated by the Model Generation module.  This was
previously embedded in model_generation._process_component() and has
been extracted into its own pipeline step so that it can be configured
and run independently.

Pipeline steps:
1. Remove marginal triangles
2. Remove large triangles (configurable threshold)
3. Remove floating parts (keep largest component)
4. Clean model
5. Smooth (long operation, two-phase wait)
6. Close small holes
7. Final clean
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from module_base.parameter import Parameter
from module_base.rc_module import RCModule
from modules.rc_common.rc_delegation import RCDelegationClient


_log = logging.getLogger(__name__)


class PrepareModel(RCModule):
    """Clean up and prepare a mesh for texturing or export."""

    def __init__(self, logger: logging.Logger) -> None:
        super().__init__("Prepare Model", logger)
        self._client: Optional[RCDelegationClient] = None

    # ------------------------------------------------------------------ #
    # Parameters
    # ------------------------------------------------------------------ #

    def get_parameters(self) -> dict[str, Parameter]:
        return {
            "pm_enabled": Parameter(
                "Enable Prepare Model", "pm_e", "pm_enabled",
                bool, True,
                "Enable model preparation (mesh cleanup, smoothing, hole closing)",
                parameter_group="Prepare Model",
                prompt_user=False,
            ),
            "pm_large_triangle_threshold": Parameter(
                "Large Triangle Threshold", "pm_lt", "pm_large_triangle_threshold",
                float, 2.0,
                "Relative threshold for large triangle removal",
                parameter_group="Prepare Model",
                min_value=0.1, max_value=10.0,
            ),
            "pm_small_hole_max_edges": Parameter(
                "Small Hole Max Edges", "pm_sh", "pm_small_hole_max_edges",
                int, 5000,
                "Maximum hole edge count for automatic closure",
                parameter_group="Prepare Model",
                min_value=100, max_value=100000,
            ),
            "pm_smooth_params": Parameter(
                "Smooth XML Params", "pm_sxml", "pm_smooth_params",
                str, None,
                "Path to smoothing XML params file",
                parameter_group="Prepare Model",
                prompt_user=False,
                file_filter="*.xml",
            ),
        }

    # ------------------------------------------------------------------ #
    # Validation
    # ------------------------------------------------------------------ #

    def validate_parameters(self) -> tuple[bool, str | None]:
        base_ok, base_msg = super().validate_parameters()
        if not base_ok:
            return False, base_msg

        if not self._get_param("pm_enabled", True):
            return True, None

        return True, None

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def _get_param(self, key: str, default=None):
        """Get a parameter value with fallback."""
        p = self.params.get(key)
        if p is None:
            return default
        val = p.get_value()
        return val if val is not None else default

    def _init_client(self) -> bool:
        """Initialize the delegation client from session state or defaults."""
        # Try to get existing client info from session state
        rc_exe = self._get_param("rc_executable_path")
        if not rc_exe:
            rc_exe_paths = [
                Path("C:/Program Files/Epic Games/RealityScan_2.1/RealityScan.exe"),
                Path("C:/Program Files/Epic Games/RealityScan_2.0/RealityScan.exe"),
                Path("C:/Program Files/Epic Games/RealityScan/RealityScan.exe"),
            ]
            for p in rc_exe_paths:
                if p.exists():
                    rc_exe = str(p)
                    break

        if not rc_exe:
            self.logger.error("RealityScan executable not found")
            return False

        instance_name = self._get_param("rc_instance_name", "*")

        self._client = RCDelegationClient(
            rc_exe=rc_exe,
            instance_name=instance_name,
            poll_interval=2.0,
            logger=self.logger,
        )

        if self._progress_reporter:
            self._client.on_progress = lambda op, pct, elapsed, eta: self._report_progress(
                op, pct, elapsed, eta,
            )

        return True

    # ------------------------------------------------------------------ #
    # Main run
    # ------------------------------------------------------------------ #

    def run(self) -> dict[str, object] | None:
        if not self._get_param("pm_enabled", True):
            self.logger.info("[Prepare Model] Skipped (disabled)")
            return {"Success": True, "Skipped": True}

        if not self._init_client():
            return {"Success": False, "Error": "RealityScan executable not found"}

        self.logger.info("[Prepare Model] Starting mesh cleanup pipeline")

        try:
            # 1. Remove marginal triangles
            self._client.run_quick("Select Marginal Triangles", "-selectMarginalTriangles")
            self._client.run_quick("Remove Marginal Triangles", "-removeSelectedTriangles")

            # 2. Remove large triangles
            threshold = self._get_param("pm_large_triangle_threshold", 2.0)
            self._client.run_quick("Select Large Triangles", "-selectLargeTrianglesRel", str(threshold))
            self._client.run_quick("Remove Large Triangles", "-removeSelectedTriangles")

            # 3. Remove floating parts (keep largest component)
            self._client.run_quick("Select Largest Component", "-selectLargestModelComponent")
            self._client.run_quick("Invert Selection", "-invertTrianglesSelection")
            self._client.run_quick("Remove Floating Parts", "-removeSelectedTriangles")

            # 4. Clean
            self._client.run_quick("Clean Model", "-cleanModel")

            # 5. Smooth (long operation - use two-phase)
            smooth_args = ["-smooth"]
            smooth_xml = self._get_param("pm_smooth_params")
            if smooth_xml and os.path.isfile(smooth_xml):
                smooth_args.extend(["-setPropertyFromXml", smooth_xml])
            self._client.delegate(*smooth_args)
            self._client.wait_idle_two_phase("Smooth Model")

            # 6. Close small holes
            max_edges = self._get_param("pm_small_hole_max_edges", 5000)
            self._client.run_quick("Close Holes", "-closeHoles", str(max_edges))

            # 7. Final clean
            self._client.run_quick("Final Clean", "-cleanModel")

            self.logger.info("[Prepare Model] Mesh cleanup complete")

            return {"Success": True, "Steps Completed": 7}

        except TimeoutError as e:
            self.logger.error("[Prepare Model] Timed out: %s", e)
            return {"Success": False, "Error": str(e)}
        except Exception as e:
            self.logger.error("[Prepare Model] Failed: %s", e)
            return {"Success": False, "Error": str(e)}
